"""empty message

Revision ID: 95d05247342c
Revises: 0f023cbe11c9
Create Date: 2024-05-14 15:46:18.042894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d05247342c'
down_revision: Union[str, None] = '0f023cbe11c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflexauthsession', schema=None) as batch_op:
        batch_op.drop_index('ix_reflexauthsession_session_id')
        batch_op.create_index(batch_op.f('ix_reflexauthsession_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflexauthsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflexauthsession_session_id'))
        batch_op.create_index('ix_reflexauthsession_session_id', ['session_id'], unique=1)

    # ### end Alembic commands ###
